/* this code was generated by automated tool,
   should not edit by hand */

export interface KeywordService {
	GetTopKeywords(request: TopKeywordsRequest): Promise<TopKeywordsResponse>;
}

// deno-lint-ignore no-empty-interface
export interface TopKeywordsRequest {
}

export interface TopKeywordsResponse {
	keywords?: string[];
}
