/* this code was generated by automated tool, 
   should not edit by hand */

export interface SocialMediaService {
  CreatePost(request: Post): Promise<PostResponse>;
  UpdatePost(request: Post): Promise<PostResponse>;
  DeletePost(request: PostRequest): Promise<PostResponse>;
  GetPost(request: PostRequest): Promise<PostResponse>;
  GetPosts(request: Empty): Promise<PostList>;
  SearchPost(request: SearchRequest): Promise<PostList>;
  GetTrendingPosts(request: Empty): Promise<PostList>;
  GetTrendingKeywords(request: Empty): Promise<KeywordList>;
  RecommendPosts(request: UserRequest): Promise<PostList>;
}

export interface Post {
  id?: string;
  userId: string;
  title: string;
  content: string;
}

export interface PostRequest {
  id: string;
}

export interface PostResponse {
  success: boolean;
  message: string;
  post?: Post;
}

export interface Empty {

}

export interface PostList {
  posts?: Post[];
}

export interface KeywordList {
  keywords?: string[];
}

export interface UserRequest {
  userId: string;
}

export interface SearchRequest {
  search: string;
}
