/* this code was generated by automated tool, 
   should not edit by hand */

export interface UserService {
  CreateUser(request: CreateUserRequest): Promise<CreateUserResponse>;
  RecommendPosts(request: EmptyRequest): Promise<PostRecommendationResponse>;
}

export interface User {
  _id?: string;
  username?: string;
  password?: string;
  favoriteCategories?: string[];
  userInteraction?: UserInteraction;
  recommendedPosts?: string[];
}

export interface UserInteraction {
  likedPosts?: string[];
  bookmarkedPosts?: string[];
  clickedPosts?: string[];
}

export interface CreateUserRequest {
  username?: string;
  password?: string;
}

export interface CreateUserResponse {
  success?: boolean;
  message?: string;
}

export interface EmptyRequest {

}

export interface PostRecommendationResponse {
  postId?: string[];
}
